version: '2'
services:
  db:
    build: .
    image: 'postgres:latest'
    # environment:
      # POSTGRES_USER: 'simple_api'
      # POSTGRES_PASSWORD: 'yourpassword'
    ports:
      - '5431:5432'
    volumes:
      - 'db:/var/lib/postgresql/data'
    tty: true

  redis:
    image: 'redis:3.2-alpine'
    command: redis-server
    ports:
      - '6379:6379'
    volumes:
      - 'redis:/var/lib/redis/data'

  web:
    build: .
    command: bundle exec unicorn
    volumes:
      - .:/simple_api
    ports:
      - "8080:8080"
    depends_on:
      - 'db'
      - 'redis'
    links:
      - db
      - redis

  sidekiq:
    build: .
    depends_on:
      - 'db'
      - 'redis'
    command: bundle exec sidekiq
    volumes:
      - '.:/simple_api'
    links:
      - redis
      - db

volumes:
  redis:
  db:
