# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: c4cc7d7c38c2d0fc6b5725c50b6ffb06b52bbdd0150a78f33993ecba5b740edf7445238e53f43134fd7c471add9635ce085a4793913eb93433cbe371bb1e2d0b

test:
  secret_key_base: c164e5cc4787dba691106bfd353be639ee4ee243bee00f2dc3533d0e95bf381f229d5110ad8a25b6619ae988a5570915137775347f263131ad0d82be78788220

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
